name: school_management_system_01
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  email_validator: ^2.1.17
  wc_form_validators: ^1.0.1
  introduction_screen: ^3.1.4
  google_fonts: ^6.1.0
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  syncfusion_flutter_datagrid: ^24.1.41
  syncfusion_flutter_calendar: ^24.1.41
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.16.1
  provider: ^6.1.2
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
